spring:
  application:
    name=taco-cloud
  thymeleaf:
    cache=false
  datasource:
    generate-unique-name: false
    name: tacocloud
  mongodb:
    host: localhost
    port: 27017
    username: tacocloud
    password: s3cr3tp455w0rd
    database: tacoclouddb